language: objective-c
osx_image: xcode8

before_install:
  - gem install cocoapods
  - brew update
script:
- pod repo update
- pod update
- xcodebuild -scheme 'MediaBrowser' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c